// ── AI TOOLS (powered by Anthropic API via Supabase Edge or direct) ──

async function callAI(prompt, outputId, loadingId) {
  const output = document.getElementById(outputId);
  const loading = document.getElementById(loadingId);

  output.classList.remove('show');
  loading.style.display = 'flex';

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 1000,
        messages: [{ role: 'user', content: prompt }]
      })
    });

    const data = await response.json();

    if (data.error) {
      // Fallback: generate locally for demo if API call fails
      return generateFallback(prompt, outputId, loadingId);
    }

    const text = data.content?.map(c => c.text || '').join('') || '';
    loading.style.display = 'none';
    output.textContent = text;
    output.classList.add('show');
    showToast('AI content generated!', 'success');
    await logActivity('Used AI Tool');
    return text;
  } catch (err) {
    return generateFallback(prompt, outputId, loadingId);
  }
}

function generateFallback(prompt, outputId, loadingId) {
  const output = document.getElementById(outputId);
  const loading = document.getElementById(loadingId);

  // Context-aware fallback content
  let text = '';
  if (prompt.includes('CV') || prompt.includes('resume')) {
    text = generateSampleCV(prompt);
  } else if (prompt.includes('personal statement')) {
    text = generateSamplePS(prompt);
  } else if (prompt.includes('motivation letter')) {
    text = generateSampleML(prompt);
  } else {
    text = `[AI Preview Mode]\n\nThis is a preview of the AI-generated content. Connect your Anthropic API key in Supabase Edge Functions to enable full AI generation.\n\nYour input has been received and would be processed by Claude AI to generate professional, personalized content tailored to your academic background and goals.`;
  }

  setTimeout(() => {
    loading.style.display = 'none';
    output.textContent = text;
    output.classList.add('show');
  }, 1500);
}

function generateSampleCV(prompt) {
  const name = document.getElementById('cvName')?.value || 'Your Name';
  const edu = document.getElementById('cvEducation')?.value || 'Bachelor of Science, University';
  const skills = document.getElementById('cvSkills')?.value || 'Research, Communication, Leadership';
  return `${name.toUpperCase()}
${'─'.repeat(50)}
📧 email@example.com | 📞 +250 700 000 000 | LinkedIn: linkedin.com/in/${name.toLowerCase().replace(/\s/g,'')}

EDUCATION
─────────────────────────────────────────────────
${edu}
• Relevant coursework: Research Methods, Academic Writing, Statistics

SKILLS
─────────────────────────────────────────────────
${skills.split(',').map(s => `• ${s.trim()}`).join('\n')}

EXPERIENCE
─────────────────────────────────────────────────
• Academic Research Assistant – University Department
• Community Volunteer – Local NGO (2022–2023)
• Student Representative – Faculty Council

AWARDS & ACHIEVEMENTS
─────────────────────────────────────────────────
• Academic Excellence Award, 2023
• Best Research Paper, Annual Conference 2023

LANGUAGES
─────────────────────────────────────────────────
• English (Fluent) • Kinyarwanda (Native) • French (Intermediate)

[Generated by AdmissionIQ AI — personalize further with your details]`;
}

function generateSamplePS(prompt) {
  const course = document.getElementById('psCourse')?.value || 'Computer Science';
  const uni = document.getElementById('psUni')?.value || 'the University';
  const goals = document.getElementById('psGoals')?.value || 'contribute to African tech development';
  return `PERSONAL STATEMENT — ${course.toUpperCase()}

Growing up in East Africa, I witnessed firsthand the transformative power of education in lifting communities out of poverty. This experience, combined with my passion for ${course}, has shaped my academic journey and my determination to pursue advanced studies at ${uni}.

Throughout my undergraduate studies, I have consistently demonstrated both academic excellence and a commitment to applying theoretical knowledge to real-world challenges. My coursework in ${course} provided me with a rigorous foundation, while extracurricular activities such as student research projects and community tutoring have honed my leadership and communication skills.

What particularly draws me to ${uni} is its world-class faculty, its commitment to interdisciplinary research, and its diverse and vibrant academic community. I am especially interested in the department's ongoing work in areas that directly align with my goal to ${goals}.

My long-term vision is to return to Africa equipped with the skills and knowledge necessary to drive meaningful change. I believe that the training and global perspective I would gain from this program would be instrumental in achieving this goal.

I am confident that I would bring a unique perspective, unwavering dedication, and a genuine hunger for knowledge to your program. Thank you for considering my application.

[Generated by AdmissionIQ AI — personalize with your specific experiences]`;
}

function generateSampleML(prompt) {
  const scholarship = document.getElementById('mlScholarship')?.value || 'this scholarship';
  const goals = document.getElementById('mlGoals')?.value || 'advance my career in my field';
  return `MOTIVATION LETTER — APPLICATION FOR ${scholarship.toUpperCase()}

Dear Selection Committee,

It is with great enthusiasm and a deep sense of purpose that I write to express my interest in ${scholarship}. As a young African scholar committed to excellence and community development, I believe this opportunity aligns perfectly with my academic aspirations and long-term career goals.

My academic journey has been defined by a relentless pursuit of knowledge and a determination to overcome obstacles that often limit students from developing countries. Despite financial constraints, I maintained a competitive GPA and actively engaged in research activities that have strengthened both my analytical skills and my resolve to pursue graduate-level education.

The scholarship would not only alleviate the financial burden of my studies but would also allow me to fully dedicate myself to my academic pursuits. My goal is to ${goals}, and I firmly believe that the support from this scholarship would be a catalyst in making this vision a reality.

I am committed to being an ambassador for this scholarship program, inspiring other young Africans to pursue education with the same passion and tenacity. I pledge to give back to my community and to Africa at large upon the completion of my studies.

I would be deeply honored to be selected for this prestigious scholarship and would welcome the opportunity to discuss my candidacy further.

Yours faithfully,
[Your Name]

[Generated by AdmissionIQ AI — personalize with your story]`;
}

// ── AI CV BUILDER ──
async function generateCV() {
  const name = document.getElementById('cvName').value.trim();
  const education = document.getElementById('cvEducation').value.trim();
  const skills = document.getElementById('cvSkills').value.trim();
  const experience = document.getElementById('cvExperience').value.trim();
  const projects = document.getElementById('cvProjects').value.trim();

  if (!name || !education) return showToast('Please fill in your name and education', 'error');

  const prompt = `Create a professional academic CV for a student applying to international universities. 
Name: ${name}
Education: ${education}
Skills: ${skills}
Experience: ${experience}
Projects: ${projects}

Format it as a clean, professional text CV with sections for: Personal Info, Education, Skills, Experience, Projects, Achievements. Make it compelling for international university admissions.`;

  await callAI(prompt, 'cvOutput', 'cvLoading');
}

async function copyOutput(id) {
  const el = document.getElementById(id);
  if (!el || !el.textContent) return showToast('Nothing to copy', 'error');
  await navigator.clipboard.writeText(el.textContent);
  showToast('Copied to clipboard!', 'success');
}

// ── AI PERSONAL STATEMENT ──
async function generatePS() {
  const course = document.getElementById('psCourse').value.trim();
  const uni = document.getElementById('psUni').value.trim();
  const achievements = document.getElementById('psAchievements').value.trim();
  const goals = document.getElementById('psGoals').value.trim();

  if (!course || !uni) return showToast('Please fill in course and university', 'error');

  const prompt = `Write a compelling personal statement for a university application.
Course: ${course}
University: ${uni}
Achievements: ${achievements}
Goals: ${goals}

Write a 500-600 word personal statement that is engaging, specific, and highlights the student's passion for the subject, relevant experiences, and future aspirations. Make it suitable for an African student applying internationally.`;

  await callAI(prompt, 'psOutput', 'psLoading');
}

// ── AI MOTIVATION LETTER ──
async function generateML() {
  const scholarship = document.getElementById('mlScholarship').value.trim();
  const background = document.getElementById('mlBackground').value.trim();
  const goals = document.getElementById('mlGoals').value.trim();

  if (!scholarship) return showToast('Please enter the scholarship name', 'error');

  const prompt = `Write a professional scholarship motivation letter.
Scholarship: ${scholarship}
Applicant Background: ${background}
Career Goals: ${goals}

Write a compelling 400-500 word motivation letter that demonstrates the applicant's suitability for the scholarship, their academic achievements, and how this scholarship will help them achieve their goals. The tone should be professional yet personal.`;

  await callAI(prompt, 'mlOutput', 'mlLoading');
}

// ── AI UNIVERSITY MATCHER ──
function matchUniversities() {
  const grades = parseFloat(document.getElementById('matchGrades').value) || 0;
  const budget = parseFloat(document.getElementById('matchBudget').value) || 50000;
  const program = document.getElementById('matchProgram').value.toLowerCase();
  const countries = document.getElementById('matchCountries').value.toLowerCase();

  // Rules-based matching engine
  let matches = UNIVERSITIES_DATA.filter(uni => {
    // Budget filter
    if (uni.tuition_usd > budget) return false;
    // Program filter
    if (program && !uni.degrees.some(d => d.toLowerCase().includes(program))) return false;
    // Country preference
    if (countries && !uni.country.toLowerCase().includes(countries)) return false;
    return true;
  });

  // Sort by ranking
  matches.sort((a, b) => a.ranking - b.ranking);

  // Score each match
  const scoredMatches = matches.map(uni => {
    let score = 100;
    // Ranking bonus
    if (uni.ranking <= 100) score += 30;
    else if (uni.ranking <= 500) score += 20;
    else if (uni.ranking <= 1000) score += 10;
    // Budget fit
    const budgetRatio = uni.tuition_usd / budget;
    if (budgetRatio < 0.5) score += 20;
    else if (budgetRatio < 0.8) score += 10;
    return { ...uni, score };
  });

  scoredMatches.sort((a, b) => b.score - a.score);

  const output = document.getElementById('matchOutput');
  if (scoredMatches.length === 0) {
    output.innerHTML = `<div class="empty-state"><div class="icon">🔍</div><h3>No matches found</h3><p>Try adjusting your budget or program preferences</p></div>`;
  } else {
    output.innerHTML = `
      <div style="font-weight:600;margin-bottom:16px">🎯 Found ${scoredMatches.length} matching universities:</div>
      ${scoredMatches.slice(0, 6).map((uni, i) => `
        <div style="display:flex;align-items:center;gap:14px;padding:14px;background:var(--bg-card);border:1px solid var(--border);border-radius:var(--radius-sm);margin-bottom:10px">
          <div style="width:28px;height:28px;background:var(--gradient-2);border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:0.8rem;color:white;flex-shrink:0">${i+1}</div>
          <span style="font-size:1.4rem">${uni.flag}</span>
          <div style="flex:1">
            <div style="font-weight:600;font-size:0.92rem">${uni.name}</div>
            <div style="font-size:0.8rem;color:var(--text-secondary)">${uni.country} • Rank #${uni.ranking} • ${uni.tuition}/yr</div>
          </div>
          <span class="tag tag-green">${uni.score}% match</span>
        </div>
      `).join('')}
    `;
  }
  output.classList.add('show');
}
